version: 2

project_name: kibana-cli

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/kibana-cli
    binary: kibana-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/fatecannotbealtered/kibana-cli/cmd.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: false
    files:
      - none*

checksum:
  name_template: checksums.txt

release:
  skip_existing: true
